### ISSUE TITLE
not found FormItPluginUtils.mod.js

### ISSUE THREAD

**Issue by ideook** [FormIt3D/SharedPluginUtilities#2]
There is no FormItPluginUtils.mod.js file in this repository. Or where can I find the currentUnits function?

**Comment by jhauswirth** [comment]
Those files aren't supported anymore, but the code still works and you can get the code here
https://github.com/FormIt3D/FormItExamplePlugins/tree/master/SharedPluginFiles

**Comment by jhauswirth** [comment]
If you have a plugin repo you're trying to get working, I can look at it and help fix it.
